### ISSUE TITLE
Allows passing of custom build options to `build_docker_image`

### ISSUE THREAD

**Issue by desertaxle** [PrefectHQ/prefect-docker#46]
Add a `platform` option to `build_docker_image` to allow building images for different platforms. Should accomplish the same result as using the `--platform` option with the `docker build` CLI (e.g., `docker build --platform=linux/amd64`)

**Comment by ngriffiths13** [comment]
It would actually be great if we could expose a lot of the build options from docker. For example, in order for our CI/CD to run, we need to build a docker image that has GCP credentials and so we pass it --network. And I think there would be other useful options as well.
